export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const SAVE_NEW_RECIPE = 'SAVE_NEW_RECIPE';
export const FETCH_RECIPES_BEGIN   = 'FETCH_RECIPES_BEGIN';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export const RECIPES_FETCHED = 'RECIPES_FETCHED';
export const GET_RECIPE_DETAILS = 'GET_RECIPE_DETAILS';